language: cpp
compiler: 
  - g++
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.9
before_script:
  - cd ./AVLTree
script:
  - g++-4.9 --version
  - g++-4.9 *.h* *.cpp -std=gnu++0x
  - ./a.out