sudo: false
language: cpp
compiler: 
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5.1
before_script:
  - cd ./RPNCalculator
script:
  - g++-5.1 --version
  - g++-5.1 *.h* *.cpp -std=gnu++0x
  - ./a.out
